PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Controllers/PeriodicalController.cs
using Library.Models;
using Library.Repositories.Interfaces;
using Library.Services;
using Library.Utilities;
using Library.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PeriodicalController : Controller
    {
        private IPeriodicalService _periodical;
        private IUnitOfWork _unitOfWork;
        private ILanguageService _languageService;
        private IPublisherService _publisherService;
        private ICategoryService _categoryService;

        public PeriodicalController(IPeriodicalService periodical, IUnitOfWork unitOfWork, IPublisherService publisherService, 
            ICategoryService categoryService, ILanguageService languageService)
        {
            _periodical = periodical;
            _unitOfWork = unitOfWork;
            _publisherService = publisherService;
            _categoryService = categoryService;
            _languageService = languageService;
        }

        public IActionResult Index(string searchTerm, int pageNumber = 1, int pageSize = 10)
        {
            PagedResult<PeriodicalViewModel> result;

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                result = _periodical.GetPeriodicalByName(searchTerm, pageNumber, pageSize);
            }
            else
            {
                result = _periodical.GetAll(pageNumber, pageSize);
            }

            ViewBag.SearchTerm = searchTerm;
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            var model = new PeriodicalViewModel
            {
                ItemCode = _periodical.GenerateNextPeriodicalCode(),
                Languages = await _languageService.GetAllAsync(),
                Publishers = await _publisherService.GetAllAsync(),
                Categories = await _categoryService.GetAllAsync(),

                FrequencyList = Enum.GetValues(typeof(Frequency))
                    .Cast<Frequency>()
                    .Select(f => new SelectListItem
                    {
                        Value = f.ToString(),
                        Text = f.ToString()
                    })

            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PeriodicalViewModel vm)
        {
            
            if (!ModelState.IsValid)
            {
                await PopulateDropdowns(vm);
            }

            vm.ItemCode = _periodical.GenerateNextPeriodicalCode();

            string result = _periodical.InsertPeriodical(vm);

            if (result == "Periodical already exists.")
            {
                TempData["ErrorMessage"] = result;
            }
            else
            {
                TempData["SuccessMessage"] = $"{vm.Title} successfully added!";
            }

            return RedirectToAction(nameof(Create));

        }

        public IActionResult Delete(int id)
        {
            var entity = _unitOfWork.GenericRepository<Periodical>().GetById(id);
            if (entity == null)
                return NotFound();

            _unitOfWork.GenericRepository<Periodical>().Delete(entity);
            _unitOfWork.Save();

            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var periodical = _periodical.GetPeriodicalById(id);
            if (periodical == null) return NotFound();

            var vm = new PeriodicalViewModel
            {
                Id = periodical.Id,
                Title = periodical.Title,
                ISSN = periodical.ISSN,
                PublishedYear = periodical.PublishedYear,
                LanguageId = periodical.LanguageId,
                CategoryId = periodical.CategoryId,
                PublisherId = periodical.PublisherId,
                Description = periodical.Description,
                Theme = periodical.Theme,
                ItemCode = periodical.ItemCode,
                Frequency = periodical.Frequency,

                Languages = await _languageService.GetAllAsync(),
                Publishers = await _publisherService.GetAllAsync(),
                Categories = (await _categoryService.GetAllAsync())
                    .Where(c => c.ItemType == ItemType.Periodical).ToList(),

                FrequencyList = Enum.GetValues(typeof(Frequency))
                .Cast<Frequency>()
                .Select(f => new SelectListItem
                {
                    Value = f.ToString(),
                    Text = f.ToString(),
                    Selected = (f == periodical.Frequency)
                })
            };
    
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PeriodicalViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                vm.Languages = await _languageService.GetAllAsync();
                vm.Publishers = await _publisherService.GetAllAsync();
                vm.Categories = (await _categoryService.GetAllAsync())
                    .Where(c => c.ItemType == ItemType.Periodical).ToList();

            }

            var periodical = _unitOfWork.GenericRepository<Periodical>().GetById(vm.Id);
            if (periodical == null)
                return NotFound();

            periodical.Id = vm.Id;
            periodical.Title = vm.Title;
            periodical.ItemCode = vm.ItemCode;
            periodical.PublishedYear = vm.PublishedYear;
            periodical.LanguageId = vm.LanguageId;
            periodical.CategoryId = vm.CategoryId;
            periodical.PublisherId = vm.PublisherId;
            periodical.Description = vm.Description;
            periodical.ISSN = vm.ISSN;
            periodical.Frequency = vm.Frequency;
            periodical.Theme = vm.Theme;

            _unitOfWork.GenericRepository<Periodical>().Update(periodical);
            _unitOfWork.Save();

            vm.FrequencyList = Enum.GetValues(typeof(Frequency))
                    .Cast<Frequency>()
                    .Select(e => new SelectListItem
                    {
                        Value = e.ToString(),
                        Text = e.ToString(),
                        Selected = (vm.Frequency == e)
                    });

            TempData["SuccessMessage"] = $"{vm.Title} updated successfully !";

            return View(vm);
        }

        private async Task PopulateDropdowns(PeriodicalViewModel vm)
        {
            vm.Languages = await _languageService.GetAllAsync();
            vm.Publishers = await _publisherService.GetAllAsync();
            vm.Categories = await _categoryService.GetAllAsync();

        }
    }
}

PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Member/Controllers/PeriodicalController.cs
using Library.Repositories.Interfaces;
using Library.Services;
using Library.Utilities;
using Library.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSystem.Areas.Member.Controllers
{
    [Area("Member")]
    public class PeriodicalController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IPeriodicalService _periodicalService;

        public PeriodicalController(IUnitOfWork unitOfWork, IPeriodicalService periodicalService)
        {
            _unitOfWork = unitOfWork;
            _periodicalService = periodicalService;
        }

        public IActionResult Index(string searchTerm, int pageNumber = 1, int pageSize = 10)
        {

            PagedResult<PeriodicalViewModel> result;

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                result = _periodicalService.GetPeriodicalByName(searchTerm, pageNumber, pageSize);
            }
            else
            {
                result = _periodicalService.GetAll(pageNumber, pageSize);
            }

            ViewBag.SearchTerm = searchTerm;
            return View(result);
        }
    }
}

PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Views/Periodical/Create.cshtml
@using Library.Models;
@using Library.ViewModels;
@model Library.ViewModels.PeriodicalViewModel

@{
    ViewData["Title"] = "Create";
}


<style>
    .placeholder-option {
        color: #6c757d;
    }
</style>

<h1>Agregar nueva publicación periódica</h1>

<hr />
<div class="container mt-3">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label asp-for="ItemCode" class="control-label"></label>
                <input asp-for="ItemCode" class="form-control" readonly />
                <span asp-validation-for="ItemCode" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="LanguageId" class="control-label required">Idioma<span class="text-danger">
                        *</span></label>
                <select asp-for="LanguageId"
                    asp-items="@(new SelectList(Model.Languages, nameof(LanguageViewModel.Id), nameof(LanguageViewModel.Name)))"
                    class="form-control">
                    <option value="" disabled selected class="placeholder-option">-- Selecciona idioma --</option>
                </select>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="Title" class="control-label required">Título<span class="text-danger"> *</span></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="CategoryId" class="control-label required">Categoría del ítem<span class="text-danger">
                        *</span></label>
                <select asp-for="CategoryId"
                    asp-items="@(new SelectList(Model.Categories.Where(c => c.ItemType == ItemType.Periodical), nameof(CategoryViewModel.Id), nameof(CategoryViewModel.Name)))"
                    class="form-control">
                    <option value="" disabled selected class="placeholder-option">-- Selecciona categoría --</option>
                </select>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="ISSN" class="control-label required">ISSN<span class="text-danger"> *</span></label>
                <input asp-for="ISSN" class="form-control" placeholder="ej.,####-#### " />
                <span asp-validation-for="ISSN" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="PublisherId" class="control-label">Editorial</label>
                <select asp-for="PublisherId"
                    asp-items="@(new SelectList(Model.Publishers, nameof(PublisherViewModel.Id), nameof(PublisherViewModel.Name)))"
                    class="form-control">
                    <option value="" disabled selected class="placeholder-option">-- Selecciona editorial --</option>
                </select>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="Description" class="control-label">Descripción</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="PublishedYear" class="control-label">Año de publicación</label>
                <select asp-for="PublishedYear" class="form-control">
                    <option value="" disabled selected class="placeholder-option">-- Selecciona año de publicación --
                    </option>
                    @for (var y = DateTime.UtcNow.Year; y >= 1900; y--)
                    {
                        <option value="@y" selected="@(Model.PublishedYear == y)">
                            @y
                        </option>
                    }
                </select>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="Frequency" class="control-label">Frecuencia<span class="text-danger"> *</span></label>
                <select asp-for="Frequency" asp-items="Model.FrequencyList" class="form-control">
                    <option value="">-- Selecciona frecuencia --</option>
                </select>
                <span asp-validation-for="Frequency" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="Theme" class="control-label">Tema<span class="text-danger"> *</span></label>
                <input asp-for="Theme" class="form-control" />
                <span asp-validation-for="Theme" class="text-danger"></span>
            </div>

        </div>

        <br />
        <div class="form-group">
            <input type="submit" value="Crear" class="btn btn-info" />
            <input type="reset" value="Limpiar" class="btn btn-info" />
        </div>

    </form>
</div>

<br />
<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Views/Periodical/Edit.cshtml
@using Library.Models;
@using Library.ViewModels;
@model Library.ViewModels.PeriodicalViewModel

@{
    ViewData["Title"] = "Edit";
}

<style>
    .placeholder-option {
        color: #6c757d;
    }
</style>

<h1>Editar detalles de la publicación periódica</h1>

<hr />
<div class="container mt-3">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label asp-for="ItemCode" class="control-label"></label>
                <input asp-for="ItemCode" class="form-control" readonly />
                <span asp-validation-for="ItemCode" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="LanguageId" class="control-label required">Idioma<span class="text-danger">
                        *</span></label>
                <select asp-for="LanguageId"
                    asp-items="@(new SelectList(Model.Languages, nameof(LanguageViewModel.Id), nameof(LanguageViewModel.Name)))"
                    class="form-control">
                    <option value="" disabled selected class="placeholder-option">-- Selecciona idioma --</option>
                </select>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="Title" class="control-label required">Título<span class="text-danger"> *</span></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="CategoryId" class="control-label required">Categoría del ítem<span class="text-danger">
                        *</span></label>
                <select asp-for="CategoryId"
                    asp-items="@(new SelectList(Model.Categories.Where(c => c.ItemType == ItemType.Periodical), nameof(CategoryViewModel.Id), nameof(CategoryViewModel.Name)))"
                    class="form-control">
                    <option value="" disabled selected class="placeholder-option">-- Selecciona categoría --</option>
                </select>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="ISSN" class="control-label required">ISSN<span class="text-danger"> *</span></label>
                <input asp-for="ISSN" class="form-control" placeholder="ej.,####-#### " />
                <span asp-validation-for="ISSN" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="PublisherId" class="control-label">Editorial</label>
                <select asp-for="PublisherId"
                    asp-items="@(new SelectList(Model.Publishers, nameof(PublisherViewModel.Id), nameof(PublisherViewModel.Name)))"
                    class="form-control">
                    <option value="" disabled selected class="placeholder-option">-- Selecciona editorial --</option>
                </select>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="Description" class="control-label">Descripción</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="PublishedYear" class="control-label">Año de publicación</label>
                <select asp-for="PublishedYear" class="form-control">
                    <option value="" disabled selected class="placeholder-option">-- Selecciona año de publicación --
                    </option>
                    @for (var y = DateTime.UtcNow.Year; y >= 1900; y--)
                    {
                        <option value="@y" selected="@(Model.PublishedYear == y)">
                            @y
                        </option>
                    }
                </select>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="Frequency" class="control-label">Frecuencia<span class="text-danger"> *</span></label>
                <select asp-for="Frequency" asp-items="Model.FrequencyList" class="form-control">
                    <option value="">-- Selecciona frecuencia --</option>
                </select>
                <span asp-validation-for="Frequency" class="text-danger"></span>
            </div>

            <div class="col-md-6 form-group">
                <label asp-for="Theme" class="control-label">Tema<span class="text-danger"> *</span></label>
                <input asp-for="Theme" class="form-control" />
                <span asp-validation-for="Theme" class="text-danger"></span>
            </div>

        </div>

        <div class="form-group">
            <br />
            <input type="submit" value="Guardar" class="btn btn-info" />
        </div>

    </form>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Views/Periodical/Index.cshtml
@using Library.Utilities
@model PagedResult<Library.ViewModels.PeriodicalViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Publicaciones periódicas</h1>

<form asp-action="Index" method="get">
    <input type="text" name="searchTerm" value="@ViewBag.SearchTerm" style="width: 400px"
        placeholder="Buscar por título de publicación" />
    <button type="submit" class="btn btn-primary">Buscar</button>
    <a asp-action="Index" class="btn btn-primary">Limpiar</a>
</form>
<p>
    <a asp-action="Create" class="btn btn-secondary">Crear nueva publicación periódica</a>
</p>
<table class="table table-stripped">
    <thead>
        <tr>
            <th>
                Código de ítem
            </th>
            <th>
                Título
            </th>
            <th>
                ISSN
            </th>
            <th>
                Frecuencia
            </th>

            <th>
                Tema
            </th>

            <th>
                Idioma
            </th>
            <th>
                Categoría
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ISSN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Frequency)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Theme)

                <td>
                    @Html.DisplayFor(modelItem => item.Language.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>


                <td>
                    <div class="d-flex gap-2">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-dark">Editar</a> |
                        <button class="btn btn-sm btn-danger"
                            onclick="openDeleteModal(@item.Id, '@item.Title', '@ViewContext.RouteData.Values["controller"]')">Eliminar</button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

<cs-pager cs-paging-pagesize=(int)Model.PageSize cs-paging-pagenumber=(int)Model.PageNumber
    cs-paging-totalitems=(int)Model.TotalItems cs-pagenumber-param="pageNumber" asp-controller="Periodical"
    asp-action="Index" cs-pager-li-current-class="page-item active" cs-pager-li-other-class="page-item"
    cs-pager-li-non-active-class="page-item disabled" cs-pager-link-current-class="page-link"
    cs-pager-link-other-class="page-link">
</cs-pager>