PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Controllers/FieldOfStudyController.cs
using Library.Models;
using Library.Repositories.Interfaces;
using Library.Services;
using Library.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FieldOfStudyController : Controller
    {
        private IFieldOfStudyService _fieldOfStudyService;
        private IUnitOfWork _unitOfWork;

        public FieldOfStudyController(IFieldOfStudyService fieldOfStudyService, IUnitOfWork unitOfWork)
        {
            _fieldOfStudyService = fieldOfStudyService;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(int pageNumber = 1, int pageSize = 10)
        {
            var vm = new FieldOfStudyViewModel
            {
                PagedFields = _fieldOfStudyService.GetAll(pageNumber, pageSize)
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult CreateorUpdate(FieldOfStudyViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                vm.PagedFields = _fieldOfStudyService.GetAll(1, 10);
                
            }

            if (vm.Id == 0)
            {
                var result = _fieldOfStudyService.InsertField(vm);
                if (result == "Field already exists.")
                {
                    TempData["ErrorMessage"] = result;
                }
                else
                {
                    TempData["SuccessMessage"] = $"{vm.Name} successfully Added!";
                }

                ModelState.Clear();
            }
            else
            {
                _fieldOfStudyService.UpdateField(vm);
                TempData["SuccessMessage"] = $"{vm.Name} updated successfully !";
                ModelState.Clear();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var field = _fieldOfStudyService.GetFieldById(id);
            if (field == null)
                return NotFound();

            var pagedData = _fieldOfStudyService.GetAll(1, 10);

            var vm = new FieldOfStudyViewModel
            {
                Id = field.Id,
                Name = field.Name,
                PagedFields = pagedData
            };

            return View("Index", vm);
        }

        public IActionResult Delete(int id)
        {
            var entity = _unitOfWork.GenericRepository<FieldOfStudy>().GetById(id);
            if (entity == null)
                return NotFound();

            _unitOfWork.GenericRepository<FieldOfStudy>().Delete(entity);
            _unitOfWork.Save();

            return Ok();
        }
    }
}

PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Views/FieldOfStudy/Index.cshtml
@using Library.Utilities
@model Library.ViewModels.FieldOfStudyViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Áreas de estudio</h1>

<div class="row">
    <div class="col-md-7">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        Nombre
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PagedFields?.Data)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>

                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-dark">Editar</a> |
                            <button class="btn btn-danger"
                                onclick="openDeleteModal(@item.Id, '@item.Name', '@ViewContext.RouteData.Values["controller"]')">Eliminar</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-5">
        <form asp-action="CreateorUpdate" method="post">
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <br />
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>

    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<cs-pager cs-paging-pagesize=(int)Model.PagedFields.PageSize cs-paging-pagenumber=(int)Model.PagedFields.PageNumber
    cs-paging-totalitems=(int)Model.PagedFields.TotalItems cs-pagenumber-param="pageNumber"
    asp-controller="FieldOfStudy" asp-action="Index" cs-pager-li-current-class="page-item active"
    cs-pager-li-other-class="page-item" cs-pager-li-non-active-class="page-item disabled"
    cs-pager-link-current-class="page-link" cs-pager-link-other-class="page-link">
</cs-pager>