PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Admin/Controllers/JournalController.cs
using Library.Models;
using Library.Repositories.Interfaces;
using Library.Services;
using Library.Utilities;
using Library.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;
using System.Threading.Tasks;

namespace LibraryManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class JournalController : Controller
    {
        private IJournalService _journal;
        private ILanguageService _languageService;
        private IUnitOfWork _unitOfWork;
        private IPublisherService _publisherService;
        private ICategoryService _categoryService;
        private IFieldOfStudyService _fieldOfStudyService;

        public JournalController(IJournalService journal, IUnitOfWork unitOfWork, 
            ILanguageService languageService, IPublisherService publisherService, ICategoryService categoryService, 
            IFieldOfStudyService ofStudyService)
        {
            _journal = journal;
            _unitOfWork = unitOfWork;
            _languageService = languageService;
            _publisherService = publisherService;
            _categoryService = categoryService;
            _fieldOfStudyService = ofStudyService;
        }

        public IActionResult Index(string searchTerm, int pageNumber = 1, int pageSize = 10)
        {
            PagedResult<JournalViewModel> result;

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                result = _journal.GetJournalByName(searchTerm, pageNumber, pageSize);
            }
            else
            {
                result = _journal.GetAll(pageNumber, pageSize);
            }

            ViewBag.SearchTerm = searchTerm;
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var journal = _journal.GetJournalById(id);
            if (journal == null) return NotFound();  

            var vm = new JournalViewModel
            {
                Id = journal.Id,
                Title = journal.Title,
                ISSN = journal.ISSN,
                PublishedYear = journal.PublishedYear,
                LanguageId = journal.LanguageId,
                CategoryId = journal.CategoryId,
                PublisherId = journal.PublisherId,
                Description = journal.Description,
                Volume = journal.Volume,
                Issue = journal.Issue,
                FieldOfStudyId = journal.FieldOfStudyId,
                ItemCode = journal.ItemCode,

                Languages = await _languageService.GetAllAsync(),
                Publishers = await _publisherService.GetAllAsync(),
                Categories = (await _categoryService.GetAllAsync())
                    .Where(c => c.ItemType == ItemType.Journal).ToList(),
                Fields = await _fieldOfStudyService.GetAllAsync()

            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(JournalViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                vm.Languages = await _languageService.GetAllAsync();
                vm.Publishers = await _publisherService.GetAllAsync();
                vm.Categories =(await _categoryService.GetAllAsync())
                    .Where(c => c.ItemType == ItemType.Journal).ToList();
                vm.Fields = await _fieldOfStudyService.GetAllAsync();

            }

            var journal = _unitOfWork.GenericRepository<Journal>().GetById(vm.Id);
            if (journal == null)
                return NotFound();

            journal.Id = vm.Id;
            journal.Title = vm.Title;
            journal.ItemCode = vm.ItemCode;
            journal.PublishedYear = vm.PublishedYear;
            journal.LanguageId = vm.LanguageId;
            journal.CategoryId = vm.CategoryId;
            journal.PublisherId = vm.PublisherId;
            journal.Description = vm.Description;
            journal.ISSN = vm.ISSN;
            journal.Volume = vm.Volume;
            journal.Issue = vm.Issue;
            journal.FieldOfStudyId = vm.FieldOfStudyId;

            _unitOfWork.GenericRepository<Journal>().Update(journal);
            _unitOfWork.Save();

            TempData["SuccessMessage"] = $"{vm.Title} updated successfully !";

            return RedirectToAction(nameof(Index));
        }
    

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var vm = new JournalViewModel
            {
                ItemCode = _journal.GenerateNextJournalCode(),
                Languages = await _languageService.GetAllAsync(),
                Publishers = await _publisherService.GetAllAsync(),
                Categories = await _categoryService.GetAllAsync(),
                Fields = await _fieldOfStudyService.GetAllAsync()   
            };
            return View(vm);

        }

        [HttpPost]
        public async Task<IActionResult> Create(JournalViewModel vm)
        {
            
            if (!ModelState.IsValid)
            {
                await PopulateDropdowns(vm);
            }

            vm.ItemCode = _journal.GenerateNextJournalCode();

            string result = _journal.InsertJournal(vm);

            if (result == "Journal already exists.")
            {
                TempData["ErrorMessage"] = result;
            }
            else
            {
                TempData["SuccessMessage"] = $"{vm.Title} successfully added!";
            }

            return RedirectToAction(nameof(Create));

        }

        public IActionResult Delete(int id)
        {
            var entity = _unitOfWork.GenericRepository<Journal>().GetById(id);
            if (entity == null)
                return NotFound();

            _unitOfWork.GenericRepository<Journal>().Delete(entity);
            _unitOfWork.Save();

            return Ok();
        }

        private async Task PopulateDropdowns(JournalViewModel vm)
        {
            vm.Languages = await _languageService.GetAllAsync();
            vm.Publishers = await _publisherService.GetAllAsync();
            vm.Categories = await _categoryService.GetAllAsync();
            vm.Fields = await _fieldOfStudyService.GetAllAsync();

        }
    }
}

PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Member/Controllers/JournalController.cs
using Library.Repositories.Interfaces;
using Library.Services;
using Library.Utilities;
using Library.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSystem.Areas.Member.Controllers
{
    [Area("Member")]
    public class JournalController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IJournalService _journalService;

        public JournalController(IUnitOfWork unitOfWork, IJournalService journalService)
        {
            _unitOfWork = unitOfWork;
            _journalService = journalService;
        }

        public IActionResult Index(string searchTerm, int pageNumber = 1, int pageSize = 10)
        {
            PagedResult<JournalViewModel> result;

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                result = _journalService.GetJournalByName(searchTerm, pageNumber, pageSize);
            }
            else
            {
                result = _journalService.GetAll(pageNumber, pageSize);
            }

            ViewBag.SearchTerm = searchTerm;
            return View(result);
        }
    }
}

PROYECTOFINAL123/LibraryManagementSystem/LibraryManagementSystem/Areas/Member/Views/Journal/Index.cshtml
@using Library.Utilities
@model PagedResult<Library.ViewModels.JournalViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Revistas</h1>

<br />
<form asp-action="Index" method="get">
    <input type="text" name="searchTerm" value="@ViewBag.SearchTerm" style="width: 400px"
        placeholder="Buscar revistas" />
    <button type="submit" class="btn btn-primary">Buscar</button>
    <a asp-action="Index" class="btn btn-primary">Limpiar</a>
</form>
<br />

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Código de revista
            </th>
            <th>
                Título
            </th>
            <th>
                ISSN
            </th>
            <th>
                Descripción
            </th>
            <th>
                Idioma
            </th>
            <th>
                Área
            </th>
            <th>
                Volumen
            </th>
            <th>
                Edición
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.ItemCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ISSN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Language.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FieldOfStudyId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Volume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Issue)
                </td>

            </tr>
        }
    </tbody>
</table>

<cs-pager cs-paging-pagesize=(int)Model.PageSize cs-paging-pagenumber=(int)Model.PageNumber
    cs-paging-totalitems=(int)Model.TotalItems cs-pagenumber-param="pageNumber" asp-controller="Journal"
    asp-action="Index" cs-pager-li-current-class="page-item active" cs-pager-li-other-class="page-item"
    cs-pager-li-non-active-class="page-item disabled" cs-pager-link-current-class="page-link"
    cs-pager-link-other-class="page-link">
</cs-pager>